
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 09 22:21:45 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FINDEC = 7;
  public static final int ENTERO = 9;
  public static final int BABRIR = 4;
  public static final int RESTA = 41;
  public static final int PUNTOCOMA = 28;
  public static final int DELETE = 19;
  public static final int WRITE = 21;
  public static final int NOIGUAL = 51;
  public static final int NOT = 52;
  public static final int MENORIGUAL = 48;
  public static final int AND = 38;
  public static final int IGUAL = 50;
  public static final int TYPE = 23;
  public static final int OR = 39;
  public static final int EVAL = 25;
  public static final int BOOL = 11;
  public static final int CALL = 24;
  public static final int DIV = 44;
  public static final int LITENT = 32;
  public static final int SUMA = 40;
  public static final int PABRIR = 2;
  public static final int IF = 14;
  public static final int MAYORIGUAL = 49;
  public static final int TABRIR = 33;
  public static final int EOF = 0;
  public static final int ASIG = 45;
  public static final int TRUE = 36;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int LITREAL = 30;
  public static final int MUL = 43;
  public static final int COMA = 27;
  public static final int MENOR = 46;
  public static final int NULL = 35;
  public static final int MOD = 42;
  public static final int PUNTERO = 34;
  public static final int MAYOR = 47;
  public static final int REAL = 10;
  public static final int ELSE = 15;
  public static final int PUNTO = 26;
  public static final int NL = 22;
  public static final int READ = 20;
  public static final int IDEN = 29;
  public static final int WHILE = 16;
  public static final int BITAND = 8;
  public static final int PROC = 13;
  public static final int STRING = 12;
  public static final int LITCADENA = 31;
  public static final int FALSE = 37;
  public static final int STRUCT = 17;
  public static final int BCERRAR = 5;
  public static final int PCERRAR = 3;
  public static final int TCERRAR = 6;
}

