package alex;

public enum ClaseLexica {
    IDEN, SUMA, RESTA, MUL, DIV, PABRIR, PCERRAR,
    BABRIR, BCERRAR, TABRIR, TCERRAR, FINDEC, ASIG, MENOR,
    MAYOR, MENORIGUAL, MAYORIGUAL, IGUAL, NOIGUAL, AND, OR,
    NOT, TRUE, FALSE, MOD, PUNTERO, BITAND, ENTERO, REAL,
    BOOL, STRING, CREARTIPO, NULL, PROC, IF, ELSE,
    WHILE, STRUCT, NEW, DELETE, READ, WRITE, NL, CALL,
    EVAL, PUNTO, COMA, LITENT, LITREAL, EOF
}
