
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 03 23:46:05 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FINDEC = 12;
  public static final int ENTERO = 28;
  public static final int BABRIR = 8;
  public static final int RESTA = 3;
  public static final int PUNTOCOMA = 48;
  public static final int WRITE = 41;
  public static final int DELETE = 39;
  public static final int NOIGUAL = 19;
  public static final int NOT = 22;
  public static final int MENORIGUAL = 16;
  public static final int AND = 20;
  public static final int IGUAL = 18;
  public static final int TYPE = 43;
  public static final int EVAL = 45;
  public static final int OR = 21;
  public static final int BOOL = 30;
  public static final int CALL = 44;
  public static final int DIV = 5;
  public static final int LITENT = 50;
  public static final int SUMA = 2;
  public static final int PABRIR = 6;
  public static final int IF = 34;
  public static final int MAYORIGUAL = 17;
  public static final int TABRIR = 10;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int TRUE = 23;
  public static final int LITREAL = 51;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int MUL = 4;
  public static final int NULL = 32;
  public static final int MENOR = 14;
  public static final int MOD = 25;
  public static final int PUNTERO = 26;
  public static final int REAL = 29;
  public static final int MAYOR = 15;
  public static final int ELSE = 35;
  public static final int PUNTO = 46;
  public static final int NL = 42;
  public static final int READ = 40;
  public static final int IDEN = 49;
  public static final int WHILE = 36;
  public static final int BITAND = 27;
  public static final int LITCADENA = 52;
  public static final int PROC = 33;
  public static final int STRING = 31;
  public static final int FALSE = 24;
  public static final int STRUCT = 37;
  public static final int BCERRAR = 9;
  public static final int PCERRAR = 7;
  public static final int TCERRAR = 11;
}

