
public enum ClaseLexica {
    FIN_DECLARACION, EOF, PYCOMA, EVAL, NOIGUAL, MAYOR, MAYOR_IGUAL,
    MENOR, MENOR_IGUAL, IGUAL, COMP_IGUALDAD, MUL, DIV, LLAVE_AP, LLAVE_CIERRE, PAREN_AP, PAREN_CIERRE,
    IDEN, ENT, REAL, MENOS, MAS,
    // Identificadores:
    LIT_AND, LIT_OR, LIT_NOT, LIT_TRUE, LIT_FALSE, LIT_TENT, LIT_TREAL, LIT_TBOOL
    // IDEN, ENT, REAL, PAP, PCIERRE, IGUAL, PYCOMA, 
    // MAS, MENOS, POR, DIV, EVALUA, DONDE, EOF
}
