package alex;

public enum ClaseLexica {
    EOF, SUMA, RESTA, MUL, DIV, PABRIR, PCERRAR,
    BABRIR, BCERRAR, TABRIR, TCERRAR, FINDEC, ASIG, MENOR,
    MAYOR, MENORIGUAL, MAYORIGUAL, IGUAL, NOIGUAL, AND, OR,
    NOT, TRUE, FALSE, MOD, PUNTERO, BITAND, ENTERO, REAL,
    BOOL, STRING, NULL, PROC, IF, ELSE, WHILE, STRUCT,
    NEW, DELETE, READ, WRITE, NL, TYPE, CALL,
    EVAL, PUNTO, COMA, PUNTOCOMA, ID, LITENT, LITREAL, LITCADENA
}
